name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1
  EB_APP_NAME: spring-boot-eb-demo
  S3_BUCKET_NAME: beantalk-bucket
  EB_ENVIRONMENT_NAME: spring-boot-eb-demo-env

jobs:
  # Build and test job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  # Deployment job (only runs on main branch pushes)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy only runs if build succeeds
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Prepare deployment package
        run: |
          # Create system.properties if it doesn't exist
          if [ ! -f system.properties ]; then
            echo "Creating system.properties with Java 17"
            echo "java.runtime.version=17" > system.properties
          fi
          
          # Create a directory for deployment
          mkdir -p deployment
          # Copy the built jar
          cp target/*.jar deployment/application.jar
          # Copy needed configuration files
          cp system.properties deployment/
          cp Procfile deployment/ 2>/dev/null || echo "No Procfile found"
          
          # Create a basic Procfile if it doesn't exist
          if [ ! -f deployment/Procfile ]; then
            echo "Creating default Procfile"
            echo "web: java -jar application.jar" > deployment/Procfile
          fi
          
          # Create zip package
          cd deployment && zip -r ../deploy.zip . && cd ..
          echo "Deployment package created successfully"

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://${{ env.S3_BUCKET_NAME }}/deploy-${{ github.sha }}.zip

      - name: Check if Elastic Beanstalk application exists
        id: check-eb-app
        run: |
          if aws elasticbeanstalk describe-applications --application-names ${{ env.EB_APP_NAME }} > /dev/null 2>&1; then
            echo "app_exists=true" >> $GITHUB_OUTPUT
          else
            echo "app_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Elastic Beanstalk application if not exists
        if: steps.check-eb-app.outputs.app_exists == 'false'
        run: |
          echo "Creating Elastic Beanstalk application: ${{ env.EB_APP_NAME }}"
          aws elasticbeanstalk create-application \
            --application-name ${{ env.EB_APP_NAME }} \
            --description "Spring Boot application"

      - name: Check if Elastic Beanstalk environment exists
        id: check-eb-env
        run: |
          if aws elasticbeanstalk describe-environments --application-name ${{ env.EB_APP_NAME }} --environment-names ${{ env.EB_ENVIRONMENT_NAME }} --query "Environments[].EnvironmentName" --output text | grep -q "${{ env.EB_ENVIRONMENT_NAME }}"; then
            echo "env_exists=true" >> $GITHUB_OUTPUT
          else
            echo "env_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Elastic Beanstalk environment if not exists
        if: steps.check-eb-env.outputs.env_exists == 'false'
        run: |
          echo "Creating Elastic Beanstalk environment: ${{ env.EB_ENVIRONMENT_NAME }}"
          aws elasticbeanstalk create-environment \
            --application-name ${{ env.EB_APP_NAME }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
            --solution-stack-name "64bit Amazon Linux 2023 v4.0.1 running Corretto 17" \
            --option-settings file://eb-config.json \
            --version-label ${{ github.sha }}

      - name: Create Elastic Beanstalk version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APP_NAME }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="${{ env.S3_BUCKET_NAME }}",S3Key="deploy-${{ github.sha }}.zip" \
            --description "Commit: ${{ github.sha }} - ${{ github.commit_message }}"

      - name: Deploy to Elastic Beanstalk environment
        if: steps.check-eb-env.outputs.env_exists == 'true'
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ env.EB_APP_NAME }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
            --version-label ${{ github.sha }}

      - name: Verify deployment
        run: |
          # Wait for deployment to complete
          echo "Waiting for deployment to complete..."
          sleep 30
          
          # Get environment health status
          HEALTH_STATUS=$(aws elasticbeanstalk describe-environments \
            --application-name ${{ env.EB_APP_NAME }} \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query "Environments[0].Health" \
            --output text)
          
          echo "Environment health status: $HEALTH_STATUS"
          
          # Check if deployment was successful
          if [ "$HEALTH_STATUS" != "Healthy" ]; then
            echo "Deployment may have issues. Checking events..."
            aws elasticbeanstalk describe-events \
              --application-name ${{ env.EB_APP_NAME }} \
              --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
              --max-items 10 \
              --query "Events[].Message"
            exit 1
          fi
          
          echo "Deployment completed successfully!"