name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1
  EB_APP_NAME: spring-boot-eb-demo
  S3_BUCKET_NAME: beantalk-bucket
  EB_ENVIRONMENT_NAME: spring-boot-eb-demo-env

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Create deployment package
        run: |
          # Create timestamp for versioning
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          
          # Create version label
          VERSION_LABEL="${{ github.sha }}-$TIMESTAMP"
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
          
          # Create deployment directory
          mkdir -p deployment
          
          # Copy JAR file from target/ directory (Maven output location)
          cp target/*.jar deployment/
          
          # Copy Procfile if it exists, otherwise create a default one
          if [ -f "Procfile" ]; then
            cp Procfile deployment/
          else
            echo "web: java -jar $(ls deployment/*.jar)" > deployment/Procfile
          fi
          
          # Copy .ebextensions directory if it exists
          cp -r .ebextensions deployment/ 2>/dev/null || true
          
          # Create zip file
          cd deployment
          zip -r ../spring-boot-app-$TIMESTAMP.zip .
          cd ..
          
          # Set zip file name
          echo "ZIP_FILE=spring-boot-app-$TIMESTAMP.zip" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_FILE s3://${{ env.S3_BUCKET_NAME }}/deployments/$ZIP_FILE
          echo "S3_OBJECT_KEY=deployments/$ZIP_FILE" >> $GITHUB_ENV

      - name: Debug - List all EB applications
        run: |
          echo "Listing all Elastic Beanstalk applications:"
          aws elasticbeanstalk describe-applications --query 'Applications[*].ApplicationName' --output table

      - name: Create Elastic Beanstalk application if needed
        run: |
          # Check if application exists by listing all and filtering
          APP_EXISTS=$(aws elasticbeanstalk describe-applications --query "Applications[?ApplicationName=='${{ env.EB_APP_NAME }}'].ApplicationName" --output text)
          
          if [ "$APP_EXISTS" = "${{ env.EB_APP_NAME }}" ]; then
            echo "Application ${{ env.EB_APP_NAME }} already exists"
          else
            echo "Creating Elastic Beanstalk application: ${{ env.EB_APP_NAME }}"
            # Create application with detailed output
            aws elasticbeanstalk create-application \
              --application-name ${{ env.EB_APP_NAME }} \
              --description "Spring Boot application"
            
            # Wait and check if application was created
            sleep 3
            NEW_APP=$(aws elasticbeanstalk describe-applications --query "Applications[?ApplicationName=='${{ env.EB_APP_NAME }}'].ApplicationName" --output text)
            
            if [ "$NEW_APP" = "${{ env.EB_APP_NAME }}" ]; then
              echo "✅ Application ${{ env.EB_APP_NAME }} created successfully"
            else
              echo "❌ ERROR: Failed to create application ${{ env.EB_APP_NAME }}"
              echo "Available applications:"
              aws elasticbeanstalk describe-applications --query 'Applications[*].ApplicationName' --output table
              exit 1
            fi
          fi

      - name: Verify application exists
        run: |
          echo "Verifying application exists before creating version..."
          APP_NAME=$(aws elasticbeanstalk describe-applications --query "Applications[?ApplicationName=='${{ env.EB_APP_NAME }}'].ApplicationName" --output text)
          
          if [ "$APP_NAME" = "${{ env.EB_APP_NAME }}" ]; then
            echo "✅ Application verified: $APP_NAME"
          else
            echo "❌ ERROR: Application ${{ env.EB_APP_NAME }} not found!"
            echo "Available applications:"
            aws elasticbeanstalk describe-applications --query 'Applications[*].ApplicationName' --output table
            exit 1
          fi

      - name: Create application version
        run: |
          echo "Creating application version: $VERSION_LABEL"
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APP_NAME }} \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=${{ env.S3_BUCKET_NAME }},S3Key=$S3_OBJECT_KEY \
            --description "Spring Boot deployment - Commit: ${{ github.sha }}"

      - name: Create or update Elastic Beanstalk environment
        run: |
          # Function to terminate environment
          terminate_environment() {
            echo "Terminating environment: ${{ env.EB_ENVIRONMENT_NAME }}"
            aws elasticbeanstalk terminate-environment \
              --environment-name ${{ env.EB_ENVIRONMENT_NAME }}
            
            # Wait for termination
            echo "Waiting for environment termination..."
            sleep 120
            
            # Check if CloudFormation stack also needs cleanup
            STACK_STATUS=$(aws cloudformation describe-stacks \
              --stack-name awseb-e-q5bzf6zhrb-stack \
              --query 'Stacks[0].StackStatus' \
              --output text 2>/dev/null || echo "NOT_FOUND")
            
            if [ "$STACK_STATUS" != "NOT_FOUND" ]; then
              echo "Deleting stuck CloudFormation stack: awseb-e-q5bzf6zhrb-stack"
              aws cloudformation delete-stack --stack-name awseb-e-q5bzf6zhrb-stack
              sleep 60
            fi
          }

          # Function to create environment
          create_environment() {
            echo "Creating Elastic Beanstalk environment: ${{ env.EB_ENVIRONMENT_NAME }}"
            
            # Get default VPC ID
            VPC_ID=$(aws ec2 describe-vpcs \
              --filters "Name=isDefault,Values=true" \
              --query "Vpcs[0].VpcId" \
              --output text)
            
            if [ "$VPC_ID" = "None" ]; then
              echo "No default VPC found, creating one..."
              VPC_ID=$(aws ec2 create-default-vpc --query 'Vpc.VpcId' --output text)
              echo "Created default VPC: $VPC_ID"
              sleep 10
            fi
            
            # Get available subnets in the default VPC
            SUBNETS=$(aws ec2 describe-subnets \
              --filters "Name=vpc-id,Values=$VPC_ID" \
              --query "Subnets[*].SubnetId" \
              --output text | tr '\t' ',')
            
            if [ -z "$SUBNETS" ]; then
              echo "No subnets found in VPC $VPC_ID, creating default subnets..."
              # Create default subnets in availability zones
              AZS=$(aws ec2 describe-availability-zones --query "AvailabilityZones[0:2].ZoneName" --output text)
              for AZ in $AZS; do
                aws ec2 create-default-subnet --availability-zone $AZ
              done
              sleep 10
              SUBNETS=$(aws ec2 describe-subnets \
                --filters "Name=vpc-id,Values=$VPC_ID" \
                --query "Subnets[*].SubnetId" \
                --output text | tr '\t' ',')
            fi
            
            echo "Using VPC: $VPC_ID"
            echo "Using subnets: $SUBNETS"
            
            # Create environment with proper configuration
            aws elasticbeanstalk create-environment \
              --application-name ${{ env.EB_APP_NAME }} \
              --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
              --solution-stack-name "64bit Amazon Linux 2023 v4.6.4 running Corretto 17" \
              --version-label $VERSION_LABEL \
              --option-settings \
                Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance \
                Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,Value=t3.micro \
                Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=aws-elasticbeanstalk-ec2-role \
                Namespace=aws:elasticbeanstalk:environment,OptionName=ServiceRole,Value=aws-elasticbeanstalk-service-role \
                Namespace=aws:ec2:vpc,OptionName=VPCId,Value=$VPC_ID \
                Namespace=aws:ec2:vpc,OptionName=Subnets,Value=$SUBNETS \
                Namespace=aws:ec2:vpc,OptionName=ELBSubnets,Value=$SUBNETS
          }

          # Check environment status
          ENV_INFO=$(aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query 'Environments[0]' \
            --output json 2>/dev/null || echo "{}")
          
          ENV_STATUS=$(echo $ENV_INFO | jq -r '.Status // "NOT_FOUND"')
          ENV_HEALTH=$(echo $ENV_INFO | jq -r '.Health // "UNKNOWN"')
          
          echo "Environment status: $ENV_STATUS"
          echo "Environment health: $ENV_HEALTH"
          
          # Handle different environment states
          case $ENV_STATUS in
            "NOT_FOUND")
              echo "Environment does not exist, creating new one..."
              create_environment
              ;;
              
            "Ready"|"Updating"|"Launching")
              echo "Environment is active, updating version..."
              aws elasticbeanstalk update-environment \
                --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
                --version-label $VERSION_LABEL
              ;;
              
            "CREATE_FAILED"|"Terminated"|"Terminating")
              echo "Environment is in failed state ($ENV_STATUS), terminating and recreating..."
              terminate_environment
              sleep 30
              create_environment
              ;;
              
            *)
              echo "Unknown environment status ($ENV_STATUS), terminating and recreating..."
              terminate_environment
              sleep 30
              create_environment
              ;;
          esac
            - name: Wait for deployment
              run: |
                echo "Waiting for deployment to complete..."
                sleep 120

      - name: Get Elastic Beanstalk environment URL
        run: |
          echo "Waiting for environment to be ready..."
          sleep 30
          
          # Get the environment endpoint URL
          EB_URL=$(aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query 'Environments[0].CNAME' \
            --output text)
          
          echo "Elastic Beanstalk Environment URL: $EB_URL"
          echo "Your application should be available at: http://$EB_URL"
          
          # Also output the status for debugging
          EB_STATUS=$(aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query 'Environments[0].Status' \
            --output text)
          
          echo "Environment Status: $EB_STATUS"

      - name: Check deployment status
        run: |
          aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query 'Environments[0].[EnvironmentName, Status, Health, VersionLabel]' \
            --output table