name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: eu-central-1
  EB_APP_NAME: spring-boot-eb-demo
  S3_BUCKET_NAME: beantalk-bucket
  EB_ENVIRONMENT_NAME: spring-boot-eb-demo-env

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Create deployment package
        run: |
          # Create timestamp for versioning
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          
          # Create version label
          VERSION_LABEL="${{ github.sha }}-$TIMESTAMP"
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
          
          # Create deployment directory
          mkdir -p deployment
          
          # Copy JAR file from target/ directory (Maven output location)
          cp target/*.jar deployment/
          
          # Copy Procfile if it exists, otherwise create a default one
          if [ -f "Procfile" ]; then
            cp Procfile deployment/
          else
            echo "web: java -jar $(ls deployment/*.jar)" > deployment/Procfile
          fi
          
          # Copy .ebextensions directory if it exists
          cp -r .ebextensions deployment/ 2>/dev/null || true
          
          # Create zip file
          cd deployment
          zip -r ../spring-boot-app-$TIMESTAMP.zip .
          cd ..
          
          # Set zip file name
          echo "ZIP_FILE=spring-boot-app-$TIMESTAMP.zip" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_FILE s3://${{ env.S3_BUCKET_NAME }}/deployments/$ZIP_FILE
          echo "S3_OBJECT_KEY=deployments/$ZIP_FILE" >> $GITHUB_ENV

      - name: Ensure Elastic Beanstalk application exists
        run: |
          # Check if application exists
          if aws elasticbeanstalk describe-applications --application-names ${{ env.EB_APP_NAME }} --query 'Applications[0].ApplicationName' --output text 2>/dev/null; then
            echo "Application ${{ env.EB_APP_NAME }} already exists"
          else
            echo "Creating Elastic Beanstalk application: ${{ env.EB_APP_NAME }}"
            aws elasticbeanstalk create-application \
              --application-name ${{ env.EB_APP_NAME }} \
              --description "Spring Boot application"
            
            # Wait a moment for application to be fully created
            sleep 5
            
            # Verify application was created
            if aws elasticbeanstalk describe-applications --application-names ${{ env.EB_APP_NAME }} --query 'Applications[0].ApplicationName' --output text; then
              echo "Application ${{ env.EB_APP_NAME }} created successfully"
            else
              echo "Failed to create application ${{ env.EB_APP_NAME }}"
              exit 1
            fi
          fi

      - name: Create application version
        run: |
          # Wait a moment to ensure application is ready
          sleep 3
          
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APP_NAME }} \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=${{ env.S3_BUCKET_NAME }},S3Key=$S3_OBJECT_KEY \
            --description "Spring Boot deployment - Commit: ${{ github.sha }}"

      - name: Create or update Elastic Beanstalk environment
        run: |
          # Check if environment exists
          if aws elasticbeanstalk describe-environments --environment-names ${{ env.EB_ENVIRONMENT_NAME }} --query 'Environments[0].EnvironmentName' --output text 2>/dev/null; then
            echo "Updating existing environment: ${{ env.EB_ENVIRONMENT_NAME }}"
            aws elasticbeanstalk update-environment \
              --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
              --version-label $VERSION_LABEL
          else
            echo "Creating Elastic Beanstalk environment: ${{ env.EB_ENVIRONMENT_NAME }}"
            aws elasticbeanstalk create-environment \
              --application-name ${{ env.EB_APP_NAME }} \
              --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
              --solution-stack-name "64bit Amazon Linux 2023 v4.0.1 running Corretto 17" \
              --version-label $VERSION_LABEL \
              --option-settings \
                Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,OptionValue=SingleInstance \
                Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,OptionValue=t3.micro
          fi

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 120

      - name: Check deployment status
        run: |
          aws elasticbeanstalk describe-environments \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query 'Environments[0].[EnvironmentName, Status, Health, VersionLabel]' \
            --output table